[build-system]
requires = ["setuptools>=65.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "easysewer"
version = "1.0.5"
authors = [
    {name = "Yiran Ji", email = "yiranji@foxmail.com"}
]
description = "An urban drainage modeling toolkit"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

dependencies = []

[project.urls]
Homepage = "https://github.com/yiranji/easysewer"
Documentation = "https://github.com/yiranji/easysewer"

[tool.setuptools]
packages = [
    "easysewer",
    "easysewer.libs",
    "easysewer.libs.win",
    "easysewer.libs.linux"
]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
easysewer = [
    "libs/win/*.esdll",
    "libs/linux/*.esso"
]

[dependency-groups]
dev = [
    "notebook>=7.3.3",
    "plotly>=6.0.1",
]
