[build-system]
requires = ["setuptools>=77.0.3", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "easysewer"
version = "2.0.0"
authors = [
    {name = "Yiran Ji", email = "yiranji@foxmail.com"}
]
description = "An urban drainage modeling toolkit"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

dependencies = []

[project.urls]
Homepage = "https://github.com/Jistill/easysewer"
Documentation = "https://github.com/Jistill/easysewer/blob/master/docs/README.md"
Source = "https://github.com/Jistill/easysewer"
Issues = "https://github.com/Jistill/easysewer/issues"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["easysewer", "easysewer.*"]
namespaces = true

[tool.setuptools.package-data]
easysewer = [
    "libs/win/*.esdll",
    "libs/linux/*.esso",
    "libs/win/*.json",
    "libs/linux/*.json"
]

[dependency-groups]
dev = [
    "notebook>=7.3.3",
    "plotly>=6.0.1",
]
