"""Independent cache samples, OUT interpolation and HOTSTART dimensions."""

from dataclasses import replace
from datetime import time, timedelta
from itertools import product
import os
from pathlib import Path
import struct
import tempfile
import unittest

from easysewer import get_native_capabilities
from easysewer.io.hotstart import HotstartData, HotstartLayout
from easysewer.io.inp import InpDocument
from easysewer.io.output_metadata import OutputMetadata
from easysewer.model import Model
from easysewer.utils import probe_library_path
from test_native_v2_groundwater import literal_groundwater
from test_native_v2_standard_io import direct_library, execute


UNITS = ('CFS', 'GPM', 'MGD', 'CMS', 'LPS', 'MLD')
FLOW = (1., 448.831, .64632, .02832, 28.317, 2.4466)
STEPS = (60., 120., 60.)
# Deliberately literal project-unit samples, not generated by the SAVE code.
SAMPLES = ((99., 2., 1., .5, .125, 2., 3., .3, 1., 2.),
           (98., 4., 2., .75, .25, -1., 4., .35, 2., 4.),
           (97., 1., .25, .125, .5, 3., 2., .2, 3., 6.))


def cache_bytes(units, samples=SAMPLES):
    return (b'SWMM5-RUNOFF' + struct.pack('<4i', 1, 2, UNITS.index(units), len(samples)) +
            b''.join(struct.pack('<11f', dt, *row) for dt, row in zip(STEPS, samples)))


def replay_model(units='CFS', tail='*', area=2):
    model = Model.from_document(InpDocument.from_text(literal_groundwater(units=units, tail=tail)), strict=True)
    model.update_options(end_date=model.effective_options.values.start_date, end_time=time(0, 4),
                         report_step=timedelta(seconds=30), routing_step=timedelta(seconds=1))
    model.subcatchments.update('S', area=area)
    return model


def out_rows(path, namespace='subcatchments'):
    raw = path.read_bytes(); meta = OutputMetadata.read(path)
    offset = meta.output_offset + 8
    for group in ('subcatchments', 'nodes', 'links', 'system'):
        key = 'swmm:' + group; width = len(dict(meta.variable_codes)[key])
        if group == namespace:
            return tuple(struct.unpack_from('<' + 'f'*width, raw, offset + i*meta.period_bytes)
                         for i in range(meta.periods))
        offset += 4*width*len(meta.names(key))
    raise AssertionError(namespace)


@unittest.skipUnless(get_native_capabilities()['swmm_solver'] and
                    get_native_capabilities()['flexible_ponding'], 'Both native solvers required')
class NativeRunoffPhysicsTests(unittest.TestCase):
    def libraries(self):
        for family, name, variable in (
            ('standard', 'swmm5', 'EASYSEWER_STANDARD_TEST_LIBRARY'),
            ('custom', 'flexible_ponding', 'EASYSEWER_CUSTOM_TEST_LIBRARY')):
            lib, _ = direct_library(os.environ.get(variable) or probe_library_path(name),
                                     revision_symbol='swmm_getEasySewerRunoffPhysics')
            self.assertEqual(lib.swmm_getEasySewerRunoffPhysics(), 1)
            yield family, lib

    def assert_samples(self, actual, samples=SAMPLES, *, initial_groundwater=0., minimum_runoff=0.):
        self.assertEqual(len(actual), 8)
        # 30 s reports lie halfway through the first/last frame and at four
        # independent positions in the longer middle frame.
        positions = ((0, .5), (0, 1.), (1, .25), (1, .5), (1, .75), (1, 1.), (2, .5), (2, 1.))
        for row, (index, fraction) in zip(actual, positions):
            current = samples[index]
            previous = samples[index-1] if index else (0.,)*5 + (initial_groundwater,) + (0.,)*4
            runoff = (1-fraction)*previous[4] + fraction*current[4]
            for col in range(1, 10):
                expected = ((1-fraction)*previous[col] + fraction*current[col]
                            if col in (1, 4, 5, 8, 9) else current[col])
                if col in (4, 8, 9) and runoff < minimum_runoff:
                    expected = 0.  # Native reporting threshold also zeros washoff.
                self.assertAlmostEqual(row[col], expected, delta=2e-6, msg=str((index, fraction, col)))
            # The legacy cache's rain column is informational: it stores the
            # last gage report value, not necessarily this hydrologic step.
            self.assertEqual(row[0], 0.)

    def test_six_flow_units_all_local_overrides_and_all_stored_fields(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory); cache = root/'runoff.bin'; state = root/'state.hsf'
            for family, lib in self.libraries():
                for units in UNITS:
                    for flags in product((False, True), repeat=4):
                        tail = ' '.join(value if enabled else '*' for value, enabled in
                                        zip(('-1', '-12', '3', '.35'), flags))
                        with self.subTest(family=family, units=units, tail=tail):
                            model = replay_model(units, tail)
                            cache.write_bytes(cache_bytes(units))
                            source = model.to_document().text + f'[FILES]\nUSE RUNOFF "{cache}"\nSAVE HOTSTART "{state}"\n'
                            self.assertFalse(any(execute(lib, root, source)))
                            flow_factor = FLOW[UNITS.index(units)]
                            land_factor = 2.2956e-5 if units in UNITS[:3] else .92903e-5
                            self.assert_samples(out_rows(root/'model.out'),
                                                minimum_runoff=2.31481e-8*(2./land_factor)*flow_factor)
                            saved = HotstartData.read(state, layout=HotstartLayout.from_model(model)).subcatchments[0]
                            length_factor = 1. if units in UNITS[:3] else .3048
                            self.assertAlmostEqual(saved.groundwater.flow, 3./flow_factor/(2./land_factor), delta=1e-12)
                            self.assertAlmostEqual(saved.groundwater.water_table, 2./length_factor, delta=1e-12)
                            self.assertAlmostEqual(saved.groundwater.moisture, .2, delta=1e-7)
                            self.assertAlmostEqual(saved.runoff, .5/flow_factor, delta=1e-12)
                            self.assertEqual(saved.runoff_quality, (3., 6.))

    def test_first_interpolation_retains_hotstart_groundwater_and_other_states(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory); cache = root/'runoff.bin'; seed = root/'seed.hsf'; saved = root/'saved.hsf'
            for family, lib in self.libraries():
                for units in ('CFS', 'CMS'):
                    with self.subTest(family=family, units=units):
                        model = replay_model(units); source = model.to_document().text
                        self.assertFalse(any(execute(lib, root, source + f'[FILES]\nSAVE HOTSTART "{seed}"\n', finish=False)))
                        layout = HotstartLayout.from_model(model)
                        initial = HotstartData.read(seed, layout=layout); row = initial.subcatchments[0]
                        area = 2./(2.2956e-5 if units == 'CFS' else .92903e-5)
                        gw = replace(row.groundwater, flow=1.5/FLOW[UNITS.index(units)]/area,
                                     maximum_infiltration_volume=.123)
                        initial = replace(initial, subcatchments=(replace(row, groundwater=gw),))
                        initial.write(seed); cache.write_bytes(cache_bytes(units))
                        self.assertFalse(any(execute(lib, root, source +
                            f'[FILES]\nUSE RUNOFF "{cache}"\nUSE HOTSTART "{seed}"\nSAVE HOTSTART "{saved}"\n')))
                        self.assert_samples(out_rows(root/'model.out'), initial_groundwater=1.5)
                        final = HotstartData.read(saved, layout=layout).subcatchments[0]
                        self.assertEqual(final.infiltration, row.infiltration)
                        self.assertEqual(final.ponded_depths, row.ponded_depths)
                        self.assertEqual(final.groundwater.maximum_infiltration_volume, .123)

    def test_zero_area_has_no_division_and_nonzero_groundwater_is_rejected(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory); cache = root/'runoff.bin'
            for family, lib in self.libraries():
                for units in ('CFS', 'CMS'):
                    with self.subTest(family=family, units=units):
                        model = replay_model(units, area=0)
                        samples = tuple((*v[:5], 0., *v[6:]) for v in SAMPLES)
                        source = model.to_document().text + f'[FILES]\nUSE RUNOFF "{cache}"\n'
                        cache.write_bytes(cache_bytes(units, samples))
                        self.assertFalse(any(execute(lib, root, source)))
                        self.assert_samples(out_rows(root/'model.out'), samples)
                        cache.write_bytes(cache_bytes(units))
                        self.assertEqual(execute(lib, root, source, finish=False), (0, 325, 325, 0))

    def test_hydrologic_ignore_options_do_not_filter_supplied_cache_flows(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory); cache = root/'runoff.bin'; cache.write_bytes(cache_bytes('CFS'))
            for family, lib in self.libraries():
                model = replay_model()
                model.update_options(ignore_rainfall=True, ignore_snowmelt=True, ignore_groundwater=True)
                with self.subTest(family=family):
                    self.assertFalse(any(execute(lib, root, model.to_document().text + f'[FILES]\nUSE RUNOFF "{cache}"\n')))
                    self.assert_samples(out_rows(root/'model.out'))

    def test_finite_cache_flow_that_cannot_be_represented_per_area_is_rejected(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory); cache = root/'runoff.bin'
            for family, lib in self.libraries():
                for units in ('CFS', 'CMS'):
                    with self.subTest(family=family, units=units):
                        model = replay_model(units, area=1e-300)
                        samples = tuple((*v[:5], 3e38, *v[6:]) for v in SAMPLES)
                        cache.write_bytes(cache_bytes(units, samples))
                        source = model.to_document().text + f'[FILES]\nUSE RUNOFF "{cache}"\n'
                        self.assertEqual(execute(lib, root, source, finish=False), (0, 325, 325, 0))

    def test_groundwater_routes_the_same_water_and_mass_as_equivalent_surface_inflow(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory); cache = root/'runoff.bin'
            for family, lib in self.libraries():
                for units in UNITS:
                    with self.subTest(family=family, units=units):
                        model = replay_model(units)
                        source = model.to_document().text + f'[FILES]\nUSE RUNOFF "{cache}"\n'
                        # A dry first frame establishes concentration 3 before
                        # either flow begins. Both pollutants have GW conc. 3.
                        groundwater = tuple((0., 0., 0., 0., 0., q, 3., .3, 3., 3.) for q in (0., 2., 3.))
                        surface = tuple((*v[:4], v[5], 0., *v[6:]) for v in groundwater)
                        outputs = []
                        for rows in (groundwater, surface):
                            cache.write_bytes(cache_bytes(units, rows))
                            self.assertFalse(any(execute(lib, root, source)))
                            outputs.append(tuple(out_rows(root/'model.out', group) for group in ('nodes', 'links')))
                        for left, right in zip(*outputs):
                            for a, b in zip(left, right):
                                for x, y in zip(a, b):
                                    self.assertAlmostEqual(x, y, delta=max(1e-7, abs(y)*2e-6))
