"""Independent custom-library qualification of shared native I/O corrections."""

from dataclasses import replace
import hashlib
import json
import os
import unittest

from easysewer import get_native_capabilities
from easysewer.runtime import FlexiblePondingBackend
from easysewer.utils import probe_library_path
from test_native_v2_standard_io import NativeIOChecks, direct_library


@unittest.skipUnless(get_native_capabilities()['flexible_ponding'], 'Custom native solver unavailable')
class NativeCustomIOTests(NativeIOChecks, unittest.TestCase):
    def setUp(self):
        path = os.environ.get('EASYSEWER_CUSTOM_TEST_LIBRARY') or probe_library_path('flexible_ponding')
        self.lib, self.library_path = direct_library(path, revision_symbol='swmm_getEasySewerNativeIOFixes')
        self.assertEqual(self.lib.swmm_getEasySewerNativeIOFixes(), 14)
        self.assertEqual(self.lib.swmm_getFlexiblePondingAbi(), 201)

    def test_build_record_pins_custom_source_shared_recipe_and_unchanged_abi(self):
        record_path = (self.library_path.with_suffix(self.library_path.suffix+'.json')
            if os.environ.get('EASYSEWER_CUSTOM_TEST_LIBRARY')
            else self.library_path.with_name('flexible_ponding.build.json'))
        record = json.loads(record_path.read_text(encoding='utf-8'))
        self.assertEqual(record['sha256'], hashlib.sha256(self.library_path.read_bytes()).hexdigest())
        self.assertEqual(record['abi'], 201)
        self.assertEqual(record['native_io_fixes'], 14)
        self.assertEqual(record['horton_outfall']['revision'], 1)
        self.assertEqual(record['horton_outfall'], record['source']['horton_outfall'])
        self.assertEqual(record['horton_outfall']['horton_state'], 1)
        self.assertEqual(record['horton_outfall']['outfall_gate'], 1)
        self.assertEqual(self.lib.swmm_getEasySewerHortonState(), 1)
        self.assertEqual(self.lib.swmm_getEasySewerOutfallGate(), 1)
        self.assertEqual(record['horton_outfall']['recipe_sha256'], record['source']['recipe']['../standard/horton_outfall.py'])
        self.assertEqual(record['horton_capacity']['revision'], 1)
        self.assertEqual(record['horton_capacity'], record['source']['horton_capacity'])
        self.assertEqual(self.lib.swmm_getEasySewerHortonCapacity(), 1)
        self.assertEqual(record['horton_capacity']['recipe_sha256'],record['source']['recipe']['../standard/horton.py'])
        self.assertEqual(record['path_io']['revision'], 1)
        self.assertEqual(record['path_io'], record['source']['path_io'])
        self.assertEqual(self.lib.swmm_getEasySewerPathIO(), 1)
        self.assertIn('scratch.c', record['path_io']['recipes'])
        self.assertEqual(record['checkpoint']['abi'], 2)
        self.assertEqual(record['checkpoint'], record['source']['checkpoint'])
        self.assertEqual(self.lib.swmm_checkpointVersion(), 2)
        self.assertEqual(record['runoff_physics'], 1)
        self.assertEqual(record['runoff_rain_clock'], 1)
        self.assertEqual(record['source']['runoff_rain_clock'], 1)
        self.assertEqual(record['rdii_io'], 1)
        self.assertEqual(record['source']['rdii_io'], 1)
        self.assertEqual(self.lib.swmm_getEasySewerRdiiIO(), 1)
        self.assertIn('../standard/rdii_io.c', record['source']['recipe'])
        self.assertEqual(record['routing_io'], 1)
        self.assertEqual(record['source']['routing_io'], 1)
        self.assertEqual(self.lib.swmm_getEasySewerRoutingIO(), 1)
        self.assertIn('../standard/routing_io.c', record['source']['recipe'])
        self.assertEqual(record['solver_output_io'], 1)
        self.assertEqual(record['source']['solver_output_io'], 1)
        self.assertEqual(self.lib.swmm_getEasySewerSolverOutputIO(), 1)
        self.assertIn('../standard/output_io.c', record['source']['recipe'])
        self.assertEqual(record['climate_io'], 1)
        self.assertEqual(record['source']['climate_io'], 1)
        self.assertEqual(self.lib.swmm_getEasySewerClimateIO(), 1)
        self.assertIn('../standard/climate_io.c', record['source']['recipe'])
        self.assertEqual(record['timeseries_io'], 1)
        self.assertEqual(record['report_io'], 1)
        self.assertEqual(record['lid_report_io'], 1)
        self.assertEqual(record['source']['timeseries_io'], 1)
        self.assertEqual(record['source']['report_io'], 1)
        self.assertEqual(record['source']['lid_report_io'], 1)
        self.assertEqual(self.lib.swmm_getEasySewerTimeSeriesIO(), 1)
        self.assertEqual(self.lib.swmm_getEasySewerReportIO(), 1)
        self.assertEqual(self.lib.swmm_getEasySewerLidReportIO(), 1)
        self.assertIn('../standard/series_io.c', record['source']['recipe'])
        self.assertIn('../standard/report_io.c', record['source']['recipe'])
        self.assertIn('../standard/runoff_rain.c', record['source']['recipe'])
        self.assertEqual(record['source']['native_io_fixes'], 14)
        self.assertEqual(record['source']['base']['commit'], '378560b3accb0e7159e97f66351cfbc67b7026bc')
        self.assertEqual(record['source']['patch'], 'easysewer:flexible-ponding:abi:201')
        self.assertIn('../standard/hotstart.py', record['source']['recipe'])
        self.assertIn('-fno-fast-math', record['command'])
        self.assertIn('-ffp-contract=off', record['command'])
        if record['target'] == 'windows':
            self.assertIn('-Wl,--image-base,0x180000000', record['command'])

    @unittest.skipIf(os.environ.get('EASYSEWER_CUSTOM_TEST_LIBRARY'), 'Installed digest qualification')
    def test_io_capability_requires_reviewed_bytes_not_only_an_abi_number(self):
        backend = FlexiblePondingBackend()
        info = backend.probe()
        self.assertTrue(info.available, info.reason)
        self.assertIn('easysewer:native-io-fixes:14', info.capabilities)
        self.assertIn('easysewer:checkpoint:2', info.capabilities)
        self.assertNotIn('easysewer:standard-fixes:16', info.capabilities)
        self.assertIn('easysewer:climate-io:1', info.capabilities)
        self.assertIn('easysewer:timeseries-io:1', info.capabilities)
        self.assertIn('easysewer:report-io:1', info.capabilities)
        self.assertIn('easysewer:lid-report-io:1', info.capabilities)
        self.assertIn('easysewer:runoff-physics:1', info.capabilities)
        self.assertIn('easysewer:runoff-rain-clock:1', info.capabilities)
        self.assertIn('easysewer:rdii-io:1', info.capabilities)
        self.assertIn('easysewer:routing-io:1', info.capabilities)
        self.assertIn('easysewer:solver-output-io:1', info.capabilities)
        self.assertEqual(dict(info.output_semantics)['swmm:runoff-rain-clock'], 'easysewer:runoff-rain-clock:1')
        self.assertEqual(dict(info.output_semantics)['swmm:runoff-replay'], 'easysewer:runoff-physics:1')
        unknown = backend.execution_info(replace(info, sha256='a'*64))
        self.assertNotIn('easysewer:native-io-fixes:14', unknown.capabilities)
        self.assertNotIn('easysewer:checkpoint:2', unknown.capabilities)
        self.assertNotIn('easysewer:climate-io:1', unknown.capabilities)
        self.assertNotIn('easysewer:timeseries-io:1', unknown.capabilities)
        self.assertNotIn('easysewer:report-io:1', unknown.capabilities)
        self.assertNotIn('easysewer:lid-report-io:1', unknown.capabilities)
        self.assertNotIn('easysewer:runoff-physics:1', unknown.capabilities)
        self.assertNotIn('easysewer:runoff-rain-clock:1', unknown.capabilities)
        self.assertNotIn('easysewer:rdii-io:1', unknown.capabilities)
        self.assertNotIn('easysewer:routing-io:1', unknown.capabilities)
        self.assertNotIn('easysewer:solver-output-io:1', unknown.capabilities)
        self.assertNotIn('swmm:runoff-rain-clock', dict(unknown.output_semantics))
        self.assertNotIn('swmm:runoff-replay', dict(unknown.output_semantics))
        self.assertEqual(info.numerical_policy,'easysewer:flexible-ponding:incremental-volume:2:native:14')
        self.assertEqual(unknown.numerical_policy,'easysewer:flexible-ponding:incremental-volume:2')
        self.assertNotIn('swmm:modified-horton',dict(unknown.output_semantics))
        self.assertNotIn('easysewer:horton-capacity:1',unknown.capabilities)


if __name__ == '__main__':
    unittest.main()
