"""Public 2.0 construction, explicit edits and INP round-trip regression checks."""
from dataclasses import replace
from datetime import datetime, timedelta
import importlib.util
from pathlib import Path
import tempfile
import unittest

from easysewer.io.inp import InpDocument
from easysewer.model import FileReference, Model, Ref
from easysewer.model.network import FunctionalStorage, Storage
from easysewer.model.resources import FileTimeSeries
from easysewer.model.values import Point
from easysewer.validation import ValidationError

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location('public_edit_example', ROOT/'examples/v2_edit_model.py')
example = importlib.util.module_from_spec(spec)
spec.loader.exec_module(example)
EVIDENCE = []

# Independent input for the edited network; not generated by the example/writer.
EDITED = '''[OPTIONS]
FLOW_UNITS CMS
INFILTRATION HORTON
FLOW_ROUTING KINWAVE
START_DATE 04/28/2023
START_TIME 08:00
END_DATE 04/28/2023
END_TIME 11:00
REPORT_START_DATE 04/28/2023
REPORT_START_TIME 08:00
DRY_DAYS 0
REPORT_STEP 0:01
WET_STEP 0:01
DRY_STEP 1:00
ROUTING_STEP 0.5
RULE_STEP 0:00:30
VARIABLE_STEP 0
[JUNCTIONS]
Upstream 5 3 0 0 0
Middle 4 3 0 0 0
[OUTFALLS]
J3 3 FREE YES
[CONDUITS]
Feeder Upstream Middle 500 0.013 0 0 .01 0
C2 Middle J3 1500 0.013 0 0 .01 0
[XSECTIONS]
Feeder CIRCULAR 0.5 0 0 0 1
C2 CUSTOM 0.75 WiderShape 0 0 1
[CURVES]
WiderShape SHAPE 0 1
WiderShape 1 1
[PATTERNS]
HourlyFlow HOURLY 1 1 1 1 1 1
HourlyFlow 1 1 1 1 1 1
HourlyFlow 1 1 1 1 1 1
HourlyFlow 1 1 1 1 1 1
[DWF]
Upstream FLOW .01 HourlyFlow
[RAINGAGES]
RainStation INTENSITY 0:01 1 TIMESERIES Storm
[TIMESERIES]
{RAIN}
[SUBCATCHMENTS]
area1 RainStation Middle 1 .2 120 .05 0
[SUBAREAS]
area1 .01 .05 0 0 0 OUTLET 100
[INFILTRATION]
area1 20 5 5 7 0
[POLYGONS]
area1 100 500
area1 300 500
area1 200 800
[COORDINATES]
Upstream 0 1000
Middle 0 500
J3 0 -1000
[CONTROLS]
RULE PausePipe
IF SIMULATION TIME >= 0:10
AND SIMULATION TIME < 0:20
THEN CONDUIT Feeder STATUS = CLOSED
ELSE CONDUIT Feeder STATUS = OPEN
PRIORITY 1
[REPORT]
SUBCATCHMENTS ALL
NODES ALL
LINKS ALL
CONTROLS YES
'''
EDITED = EDITED.replace('{RAIN}', '\n'.join(
    f'Storm {minute//60}:{minute%60:02} {30 if 10 <= minute <= 40 else 0}' for minute in range(181)))


def external_rain_text():
    return ''.join((datetime(2023, 4, 28, 8)+timedelta(minutes=minute)).strftime('%m/%d/%Y %H:%M ')
                   +str(30 if 10 <= minute <= 40 else 0)+'\n' for minute in range(181))


class EditWorkflowTests(unittest.TestCase):
    def test_example_dimensions_percentages_and_polygon(self):
        model = example.create_model()
        self.assertEqual(tuple(model.nodes), ('J1', 'J2', 'J3'))
        self.assertEqual(tuple(model.links), ('C1', 'C2'))
        self.assertEqual([(n.id, n.elevation, n.position.x, n.position.y) for n in model.nodes.values()],
                         [('J1', 5, 0, 1000), ('J2', 4, 0, 500), ('J3', 3, 0, -1000)])
        self.assertEqual([p.length for p in model.links.values()], [500, 1500])
        self.assertEqual([p.section.geometry.diameter for p in model.links.values()], [.5, .5])
        self.assertEqual([p.initial_flow for p in model.links.values()], [0, 0])
        area = model.subcatchments['area1']
        self.assertEqual((area.area, area.impervious_percent, area.width, area.slope), (1, .2, 100, .05))
        self.assertEqual(tuple((p.x, p.y) for p in area.polygon), ((100, 500), (300, 500), (200, 800)))
        self.assertEqual(area.infiltration.parameters.maximum_rate, 20)
        self.assertEqual(model.units.unit('catchment_area'), 'ha')
        self.assertEqual(model.units.unit('flow'), 'CMS')
        model.validate(for_run=True).raise_for_errors()
        EVIDENCE.append(dict(check='case2-original-fields', percentage_values=[.2, .05], nodes=3, links=2, catchments=1))

    def test_edit_updates_shared_and_composite_references_without_changing_original(self):
        original = example.create_model()
        before = original.to_json_document().data
        model = example.edit_model(original)
        self.assertEqual(original.to_json_document().data, before)
        expected = Model.from_document(InpDocument.from_text(EDITED), strict=True)
        collections = ('nodes', 'links', 'subcatchments', 'raingages', 'timeseries', 'patterns', 'curves', 'dwf', 'controls')
        for collection in collections:
            self.assertEqual(tuple(getattr(model, collection).values()), tuple(getattr(expected, collection).values()), collection)
        self.assertEqual(model.effective_options.values, expected.effective_options.values)
        self.assertEqual(model.report, expected.report)
        self.assertEqual(tuple(model.dwf), (('Upstream', 'FLOW'),))
        self.assertEqual(model.controls[('RULE', 'PausePipe')].then_actions[0].target.key, 'Feeder')
        self.assertEqual(model.links['C2'].section.geometry.curve.key, 'WiderShape')
        EVIDENCE.append(dict(check='literal-edited-graph', collections=list(collections), original_unchanged=True))

    def test_transaction_and_delete_protection_plus_explicit_cascade(self):
        model = example.edit_model(example.create_model())
        before = model.to_json_document().data
        diagnostics = example.demonstrate_protection(model)
        self.assertEqual(diagnostics['delete'], ['model.object_in_use'])
        self.assertEqual(diagnostics['transaction'], ['model.invalid_field'])
        self.assertEqual(model.to_json_document().data, before)
        doomed = model.copy()
        plan = doomed.deletion_plan(example.node('Middle'))
        self.assertEqual(set(plan), {example.node('Middle'), Ref(collection='swmm:links', key='Feeder'),
            Ref(collection='swmm:links', key='C2'), Ref(collection='swmm:subcatchments', key='area1'),
            Ref(collection='swmm:controls', key=('RULE', 'PausePipe'))})
        removed = doomed.nodes.remove('Middle', cascade=True)
        self.assertEqual(set(removed), set(plan))
        self.assertFalse(doomed.links)
        self.assertFalse(doomed.controls)
        self.assertFalse(doomed.subcatchments)
        self.assertEqual(tuple(doomed.timeseries), ('Storm',))
        self.assertEqual(tuple(doomed.patterns), ('HourlyFlow',))
        self.assertEqual(tuple(doomed.dwf), (('Upstream', 'FLOW'),))
        self.assertEqual(model.to_json_document().data, before)
        EVIDENCE.append(dict(check='atomic-edits-and-explicit-cascade', diagnostics=diagnostics, source_unchanged=True))

    def test_shared_rain_resources_and_missing_gage_validation(self):
        model = example.create_model()
        before = model.to_json_document().data
        with self.assertRaises(ValidationError):
            with model.transaction():
                model.subcatchments.update('area1', rain_gage=Ref(collection='swmm:raingages', key='*'))
        self.assertEqual(model.to_json_document().data, before)
        with self.assertRaises(ValidationError): model.timeseries.remove('Rain')
        model.timeseries.rename('Rain', 'AnotherStorm')
        self.assertEqual(model.raingages['RG'].source.series.key, 'AnotherStorm')
        self.assertEqual(tuple(model.patterns), ('DailyFlow',))
        self.assertEqual(tuple(model.dwf), (('J1', 'FLOW'),))
        EVIDENCE.append(dict(check='missing-rain-ref-and-shared-resources', original_invalid_star_rejected=True))

    def test_precision_fractional_routing_case_headers_and_mixed_polygons_survive(self):
        model = example.create_model()
        model.links.update('C1', roughness=0.0131234567890123)
        points = (Point(x=-1, y=0), Point(x=1, y=0), Point(x=0, y=1))
        model.nodes.add(Storage(id='Tank', elevation=2, max_depth=1, initial_depth=0,
            shape=FunctionalStorage(coefficient=1, exponent=1, constant=1), polygon=points))
        text = model.to_document().text
        text = '\n'.join(line.lower() if line.startswith('[') else line for line in text.splitlines())+'\n'
        reread = Model.from_document(InpDocument.from_text(text), strict=True)
        reread.subcatchments.update('area1', polygon=(*reread.subcatchments['area1'].polygon, Point(x=100, y=500)))
        output = reread.to_document()
        again = Model.from_document(output, strict=True)
        self.assertEqual(again.nodes['Tank'].polygon, points)
        self.assertEqual(len(again.subcatchments['area1'].polygon), 4)
        self.assertEqual(again.links['C1'].roughness, 0.0131234567890123)
        self.assertEqual(again.options.routing_step, timedelta(seconds=.5))
        self.assertEqual(again.to_document().to_bytes(), output.to_bytes())
        EVIDENCE.append(dict(check='historical-io-combination', routing_seconds=.5,
                             roughness=0.0131234567890123, tank_polygon_points=3, area_polygon_points=4))

    def test_external_timeseries_file_rebases_without_changing_data(self):
        with tempfile.TemporaryDirectory() as folder:
            root = Path(folder)
            data = root/'rain data.dat'
            data.write_text(external_rain_text(), encoding='utf-8')
            original = data.read_bytes()
            model = example.create_model()
            model.timeseries.replace('Rain', FileTimeSeries(id='Rain',
                file=FileReference(path='rain data.dat', base_directory=str(root))))
            target = root/'nested'
            target.mkdir()
            model.to_inp(target/'external.inp')
            reread = Model.from_inp(target/'external.inp', strict=True)
            self.assertEqual(Path(reread.timeseries['Rain'].file.resolve()).resolve(), data.resolve())
            self.assertEqual(data.read_bytes(), original)
            self.assertEqual(len(reread.timeseries), 1)
            self.assertIn('FILE', (target/'external.inp').read_text())
            EVIDENCE.append(dict(check='external-series-rebase', source_bytes_unchanged=True))


if __name__ == '__main__':
    unittest.main()
